apiVersion: v1
kind: Pod
metadata:
  name: rest-pod
  labels:
    component: rest-pod
spec:
  containers:
    - name: rest-pod
      image: rbaliyan/rest-docker
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
  restartPolicy: Always
